"""PO-token providers for the modern ``Client``.

A PO ("proof-of-origin") token is generated by a BotGuard JavaScript
challenge running in a real browser. We can't generate one in pure
Python — the BotGuard logic is private and frequently changes — but
we can plug in any external generator and cache the result for the
client lifetime.

Three provider shapes, in order of how closely they let users plug in
their existing tooling:

``CallableProvider(fn)``
    Wraps a Python callable that returns a token string. Useful when
    you've already integrated a generator into your application
    (e.g. a long-running HTTP service, an in-process JS sandbox).

``CommandProvider(cmd)``
    Shells out to a command and reads the token from stdout. Drop-in
    for tools like ``bgutil-pot`` and ``youtube-po-token-generator``
    that follow the print-the-token convention.

``ScriptProvider(script_path)``
    Runs a JavaScript file with the first available JS runtime on
    PATH (node / bun / deno; see :mod:`pyt.api._jsruntime`). Suitable
    for vendored or user-supplied generator scripts that don't ship
    their own CLI wrapper.

All three implement :class:`PoTokenProvider`, which the :class:`Client`
holds as an attribute and asks for a fresh token whenever
``AttestationRequired`` is raised. Tokens are cached so the provider
doesn't run on every request — only on the first attempt and then
again after attestation failures.
"""
from __future__ import annotations

import logging
import shlex
import subprocess  # nosec — argv built by us
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, List, Optional, Sequence, Union

from pyt.api._jsruntime import detect_runtime, run_script
from pyt.api.errors import ConfigError


logger = logging.getLogger(__name__)


# Tokens are generally good for hours. If a generator delivers one in
# less than half a second, we don't fight that — short TTLs would just
# burn the generator. Long enough to span a typical download session,
# short enough to recover gracefully if YouTube rotates the requirement.
_DEFAULT_TTL_SECONDS = 30 * 60


@dataclass
class _CachedToken:
    """Internal: a token plus when it was issued. Refreshed by the
    provider when expired or when the consumer asks us to invalidate."""

    value: str
    issued_at: float = field(default_factory=time.monotonic)

    def is_expired(self, ttl: float) -> bool:
        return (time.monotonic() - self.issued_at) > ttl


class PoTokenProvider:
    """Common interface for token generation strategies.

    Subclasses implement :meth:`_generate`. The base class handles
    caching and the ``invalidate()`` contract so the auto-retry path
    in :class:`Client` doesn't need to know which strategy is in use.
    """

    name: str = "provider"

    def __init__(self, *, ttl_seconds: float = _DEFAULT_TTL_SECONDS):
        self._ttl = ttl_seconds
        self._cache: Optional[_CachedToken] = None

    def get(self, *, force_refresh: bool = False) -> str:
        """Return a valid token, refreshing if expired or requested."""
        if not force_refresh and self._cache and not self._cache.is_expired(self._ttl):
            logger.debug("po_token[%s]: returning cached token (age %.1fs)",
                         self.name, time.monotonic() - self._cache.issued_at)
            return self._cache.value

        logger.info("po_token[%s]: generating new token (force_refresh=%s)",
                    self.name, force_refresh)
        t0 = time.monotonic()
        try:
            token = self._generate()
        except Exception as exc:
            raise ConfigError(
                f"po_token provider '{self.name}' failed: {exc}"
            ) from exc

        if not isinstance(token, str) or not token.strip():
            raise ConfigError(
                f"po_token provider '{self.name}' returned an empty token"
            )

        token = token.strip()
        elapsed = time.monotonic() - t0
        logger.info(
            "po_token[%s]: got %d-char token in %.2fs",
            self.name, len(token), elapsed,
        )
        self._cache = _CachedToken(value=token)
        return token

    def invalidate(self) -> None:
        """Drop the cached token so the next ``get()`` regenerates."""
        if self._cache is not None:
            logger.debug("po_token[%s]: invalidated cache", self.name)
        self._cache = None

    def _generate(self) -> str:
        raise NotImplementedError


# ── Concrete providers ───────────────────────────────────────────────────


class StaticProvider(PoTokenProvider):
    """A fixed token. Used when the user passes ``Client(po_token="...")``.

    No regeneration possible — invalidating just leaves the cache empty
    and the next :meth:`get` returns the same value again. If the
    server rejects this token there's nothing the provider can do
    differently.
    """

    name = "static"

    def __init__(self, token: str):
        if not isinstance(token, str) or not token.strip():
            raise ConfigError("po_token must be a non-empty string")
        super().__init__(ttl_seconds=float("inf"))
        # Pre-populate the cache so get() never calls _generate().
        self._cache = _CachedToken(value=token.strip())

    def _generate(self) -> str:
        # Should never be reached because the cache is pre-populated
        # and never expires.
        return self._cache.value if self._cache else ""

    def invalidate(self) -> None:
        # No-op: we'd return the same static value anyway.
        logger.debug("po_token[static]: invalidate() ignored — token is fixed")


class CallableProvider(PoTokenProvider):
    """Wrap a user-supplied callable.

    The callable is invoked with no arguments and must return a string.
    Exceptions are caught and re-raised as :class:`ConfigError` so the
    auto-retry path can handle them uniformly.
    """

    name = "callable"

    def __init__(self, fn: Callable[[], str], *, ttl_seconds: float = _DEFAULT_TTL_SECONDS):
        if not callable(fn):
            raise ConfigError("po_token_provider must be callable")
        super().__init__(ttl_seconds=ttl_seconds)
        self._fn = fn

    def _generate(self) -> str:
        return self._fn()


class CommandProvider(PoTokenProvider):
    """Shell out to an external command and read the token from stdout.

    The command can be a string (parsed with :func:`shlex.split`) or
    a pre-tokenized list. ``stdout`` is decoded as UTF-8; the first
    non-empty line is taken as the token.
    """

    name = "command"

    def __init__(
        self,
        command: Union[str, Sequence[str]],
        *,
        ttl_seconds: float = _DEFAULT_TTL_SECONDS,
        timeout_seconds: int = 120,
    ):
        if isinstance(command, str):
            self._argv: List[str] = shlex.split(command)
        else:
            self._argv = list(command)
        if not self._argv:
            raise ConfigError("po_token_cmd must be a non-empty command")
        super().__init__(ttl_seconds=ttl_seconds)
        self._timeout = timeout_seconds

    def _generate(self) -> str:
        logger.debug("po_token[command]: running %s", self._argv)
        result = subprocess.run(  # nosec
            self._argv,
            capture_output=True,
            check=True,
            timeout=self._timeout,
        )
        text = result.stdout.decode("utf-8", errors="replace").strip()
        # Some generators print logs to stdout before the token —
        # take the LAST non-empty line so we get the result reliably.
        for line in reversed(text.splitlines()):
            line = line.strip()
            if line:
                return line
        return text


class ScriptProvider(PoTokenProvider):
    """Run a JavaScript file with a detected runtime (node / bun / deno).

    The script is invoked once per token. Whatever's printed to stdout
    is the token (last non-empty line, same as :class:`CommandProvider`).
    """

    name = "script"

    def __init__(
        self,
        script_path: Union[str, Path],
        args: Optional[Sequence[str]] = None,
        *,
        ttl_seconds: float = _DEFAULT_TTL_SECONDS,
        timeout_seconds: int = 120,
    ):
        path = Path(script_path).expanduser().resolve()
        if not path.is_file():
            raise ConfigError(f"po_token_script not found: {script_path}")
        super().__init__(ttl_seconds=ttl_seconds)
        self._script = str(path)
        self._args = list(args or [])
        self._timeout = timeout_seconds

    def _generate(self) -> str:
        runtime = detect_runtime()
        if runtime is None:
            raise ConfigError(
                "no JavaScript runtime found on PATH. Install one of: "
                "node (https://nodejs.org), bun (https://bun.sh), "
                "deno (https://deno.com). Or run: pyt --doctor"
            )
        text = run_script(
            runtime, self._script, self._args, timeout=self._timeout,
        )
        for line in reversed(text.splitlines()):
            line = line.strip()
            if line:
                return line
        return text


# ── Coercion helper ──────────────────────────────────────────────────────


def coerce_provider(
    *,
    po_token: Optional[str] = None,
    po_token_provider: Optional[Callable[[], str]] = None,
    po_token_cmd: Optional[Union[str, Sequence[str]]] = None,
    po_token_script: Optional[Union[str, Path]] = None,
) -> Optional[PoTokenProvider]:
    """Build a :class:`PoTokenProvider` from the four user-facing
    options. At most one may be set.

    Returns ``None`` when none of the options are provided — the client
    then runs without a PO token and relies on YouTube not requiring one.
    """
    sources = [
        ("po_token", po_token),
        ("po_token_provider", po_token_provider),
        ("po_token_cmd", po_token_cmd),
        ("po_token_script", po_token_script),
    ]
    set_sources = [name for name, value in sources if value is not None]
    if len(set_sources) > 1:
        raise ConfigError(
            f"pass at most one of: {', '.join(name for name, _ in sources)} "
            f"(got: {', '.join(set_sources)})"
        )

    if po_token is not None:
        return StaticProvider(po_token)
    if po_token_provider is not None:
        return CallableProvider(po_token_provider)
    if po_token_cmd is not None:
        return CommandProvider(po_token_cmd)
    if po_token_script is not None:
        return ScriptProvider(po_token_script)
    return None
